name       : dolphin-emu
version    : 5.0.19870
release    : 58
source     :
    - git|https://github.com/dolphin-emu/dolphin.git : 032c77b462a220016f23c5079e71bb23e0ad2adf
license    : GPL-2.0-or-later
component  : games.emulator
summary    : GameCube / Wii emulator
description: |
    GameCube / Wii emulator, allowing you to play games for these two platforms on your PC.
builddeps  :
    - pkgconfig(Qt6Svg)
    - pkgconfig(alsa)
    - pkgconfig(bluez)
    - pkgconfig(fmt)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(hidapi-libusb)
    - pkgconfig(libavcodec)
    - pkgconfig(libcurl)
    - pkgconfig(libenet)
    - pkgconfig(libevdev)
    - pkgconfig(libpulse)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libzstd)
    - pkgconfig(lzo2)
    - pkgconfig(miniupnpc)
    - pkgconfig(openal)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(pugixml)
    - pkgconfig(sdl2)
    - pkgconfig(sfml-all)
    - pkgconfig(soundtouch)
    - pkgconfig(xi)
    - pkgconfig(xrandr)
    - gtest-devel
    - llvm-clang-devel
    - mbedtls-devel
optimize   : lto
setup      : |
    %cmake_ninja -DDISTRIBUTOR='Solus' \
                 -DUSE_SHARED_ENET=TRUE \
                 -DUSE_SHARED_GTEST=TRUE .
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Install udev rule
    install -Dm00644 Data/51-usb-device.rules $installdir/%libdir%/udev/rules.d/51-usb-device.rules

    # Appdata
    install -Dm00644 $pkgfiles/dolphin-emu.appdata.xml $installdir/usr/share/metainfo/dolphin-emu.appdata.xml
